from . import start_selections
from . import recorder_selections
from . import camera_selections
from . import hdd_selections
from . import switch_selections
from . import box_selections
from . import cable_selection
from . import ibp_selections
from . import gofra_selection